SLOT_SIZE = 15 # time slots size in minutes
SLOTS_PER_DAY = 24 * 60 // SLOT_SIZE
SCHEDULE_RESOLUTION = SLOTS_PER_DAY

WAKE_UP_TIME = 7
BED_TIME = 23
WAKE_UP_SLOT = (WAKE_UP_TIME * 60) // SLOT_SIZE
BED_SLOT = (BED_TIME * 60) // SLOT_SIZE