"""maundo of last migrations changes

Revision ID: 051cc65cd792
Revises: 5b11e58f4f9a
Create Date: 2026-05-24 16:10:07.692830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051cc65cd792'
down_revision = '5b11e58f4f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.drop_column('is_moveable')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moveable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('is_moveable')

    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moveable', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
