"""Created Tables: event, event_types, event_paramiters

Revision ID: 324fd8a740be
Revises: 83f6b7b073e0
Create Date: 2026-05-20 20:33:05.858401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324fd8a740be'
down_revision = '83f6b7b073e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ideal_energy', sa.Float(), nullable=False),
    sa.Column('burnout_rate', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_parameter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_parameter_id'], ['event_parameters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_types_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type_id', sa.UUID(), nullable=True),
    sa.Column('event_parameter_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_moveable', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_parameter_id'], ['event_parameters.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_events_end_time'))

    op.drop_table('events')
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_types_user_id'))

    op.drop_table('event_types')
    op.drop_table('event_parameters')
    # ### end Alembic commands ###
