"""mamoved is_moveable column from Event to EventParameters

Revision ID: 5b11e58f4f9a
Revises: ddd6f9d67652
Create Date: 2026-05-24 16:08:21.003938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b11e58f4f9a'
down_revision = 'ddd6f9d67652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moveable', sa.Boolean(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('is_moveable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_moveable', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.drop_column('is_moveable')

    # ### end Alembic commands ###
