"""empty message

Revision ID: 7fefb7dc791c
Revises: 051cc65cd792
Create Date: 2026-05-26 18:48:10.014331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fefb7dc791c'
down_revision = '051cc65cd792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.drop_column('colour')

    # ### end Alembic commands ###
