"""removed colour field from Event table

Revision ID: 9ed783c8ab7a
Revises: c7597f734e4b
Create Date: 2026-05-31 16:08:36.032241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed783c8ab7a'
down_revision = 'c7597f734e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('colour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
