"""expanded EventType fields

Revision ID: c7597f734e4b
Revises: 26ccb037005c
Create Date: 2026-05-31 16:06:44.797309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7597f734e4b'
down_revision = '26ccb037005c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_moveable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('availability_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('availability_end', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('preference_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('preference_end', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.drop_column('preference_end')
        batch_op.drop_column('preference_start')
        batch_op.drop_column('availability_end')
        batch_op.drop_column('availability_start')
        batch_op.drop_column('is_moveable')
        batch_op.drop_column('colour')

    # ### end Alembic commands ###
