"""moved colour field to Event

Revision ID: d2dbf57c407b
Revises: 7fefb7dc791c
Create Date: 2026-05-26 19:28:40.134916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dbf57c407b'
down_revision = '7fefb7dc791c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.drop_column('colour')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('colour')

    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
