"""made event parameter fields nullable

Revision ID: ddd6f9d67652
Revises: 324fd8a740be
Create Date: 2026-05-24 16:05:28.518728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd6f9d67652'
down_revision = '324fd8a740be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.alter_column('ideal_energy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('burnout_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_parameters', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('burnout_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('ideal_energy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
