
"""
    The evaluator class is responsible for evaluating the fitness of candidate schedules generated by the genetic algorithm.
    The evaluation process is comprised of two components:
        1. A fitness score based on the match between the predicted energy levels in a given timeslot and the ideal energy of the event scheduled in that timeslot (match_fitness)
            - The predicted energy levels act as heuristics to guide the search using the C process of the Two Process Model of Sleep
        2. A task yield score based on the results of a fatigue simulation that models the user's
            - Sleep pressure based on the S process of the Two Process Model
            - Fatigue build up based on intensity, consecutive hours of work, and event impact
            - Recovery during free time and sleep

    TODO:
    - Implement user time preference and constraints
    - Tune the parameters of the simulation (e.g. fatigue build up, recovery rate)
    - Implement a model for focus states and integrate into the simulation and fitness evaluation
    - Implement a more complex fatigue simulation that takes into account different types of fatigue (e.g. cognitive, physical) and different recovery rates for each type

"""
import math
from services.config import SCHEDULE_RESOLUTION, SLOT_SIZE, WAKE_UP_SLOT, BED_SLOT

WAKE_UP_TIME = 7
BED_TIME = 23

S = 0.02 # Placeholder for inital S process value used in the simulation at wakeup time
IMPORTANCE = 50 # Placeholder for event importance, to be replaced with a value defined in the Event object
K = 1 # Steepness of the yield curve - to be tuned based on experimentation (k = 1 is linear, k > 1 exponential)
FATIGUE_MODIFIER = -2.0 # Modifier for the fatigue penalty applied to task yield when effective energy is below 0
RECOVERY_RATE = 0.7 # Rate at which residual fatigue decreases during rest 
WASTE_COST_WEIGHT = 0.5
UNSCHEDULED_EVENTS_PENALTY = 1000

SLOT_HOURS = SLOT_SIZE / 60

class Evaluator:

    def __init__(self, population, energy_landscape):
        self.energy_landscape = energy_landscape

    # Given an event and a timeslot, calculate the fitness score based on ideal & required energy match
    def calculate_energy_match(self, event, timeslot):
        def calculate_resource_fit(ideal, predicted):
            gap = ideal - predicted

            if predicted > ideal:
                gap *= WASTE_COST_WEIGHT

            resource_fit = - 6*(gap ** 2)

            return resource_fit

        energy_fit = calculate_resource_fit(event.EventType.ideal_energy, timeslot.predicted_energy)

        #focus_fit = calculate_resource_fit( event.EventType.ideal_focus, timeslot.predicted_focus)

        #total_weight = (event.EventType.energy_weight + event.EventType.focus_weight)
        #avg_fit = (energy_fit * event.EventType.energy_weight + focus_fit * event.EventType.focus_weight) / total_weight

        match_score = math.exp(energy_fit)
        return max(0.0 ,match_score)

    # Given a candidate Schedule object, fetch the individuals schedule and simulate the fatigue & recovery impact
    def simulate_schedule(self, candidate):
        def calculate_s(s_inital):
            t = 30
            return (1 - (1 - s_inital) * math.exp(-SLOT_HOURS/t)) # Placeholder exponential decay function, to be replaced with a more complex function based on user state dynamics
        
        residual_fatigue = 0.0
        consecutive_active_slots = 0
        total_fitness = 0.0
        s = S

        SLOT_HOURS = SLOT_SIZE / 60
        
        positive_yield_total = 0.0
        negative_energy_penalty_total = 0.0
        sleep_penalty_total = 0.0
        fatigue_drain_total = 0.0

        # ---- SIMULATION LOOP ----
        for i in range(SCHEDULE_RESOLUTION):
            clock_slot = (i + WAKE_UP_SLOT) % SCHEDULE_RESOLUTION # Simulate a 24 hour period starting from the user's wake up time

            timeslot = candidate.timeslots[clock_slot] # Get the event scheduled for the current timeslot, if any
            predicted_energy = self.energy_landscape[clock_slot] # Get the predicted energy level for the current timeslot from the energy landscape

            effective_energy = predicted_energy - (s * 0.5) - residual_fatigue # Calculate the effective energy for the current timeslot by subtracting the effects of sleep pressure and residual fatigue from the predicted energy level

            if timeslot is not None: # If there is an event scheduled for the current timeslot, calculate the task yield and update the residual fatigue
                event = timeslot.event
                if clock_slot < BED_SLOT and clock_slot >= WAKE_UP_SLOT: # Only apply yield if the event is scheduled during waking hours
                    if effective_energy < 0: # Check if effective energy is below 0
                        task_yield = (IMPORTANCE * FATIGUE_MODIFIER) + (effective_energy * 0.5) * SLOT_HOURS # Apply a heavy penatly to task yield
                        negative_energy_penalty_total += task_yield
                    else:
                        task_yield = (IMPORTANCE * math.pow(effective_energy, K)) * SLOT_HOURS #
                        positive_yield_total += task_yield
                else:
                    task_yield = -500 * SLOT_HOURS # Heavy penalty for scheduling events during sleep hours
                    sleep_penalty_total += task_yield

                consecutive_active_slots += 1 # Increment consecutive hours of work
                consecutive_active_hours = consecutive_active_slots * SLOT_HOURS

                drain = (
                    event.EventType.impact
                    * SLOT_HOURS
                    * math.pow((1 + event.EventType.burnout_rate), consecutive_active_hours)
                ) # Calculate fatigue drain using event impact and burnout rate (alpha)
                residual_fatigue += drain # Update residual fatigue
                total_fitness += task_yield # Update total schedule fitness

                fatigue_drain_total += drain
                candidate.timeslots[clock_slot].effective_energy = effective_energy # Update effective energy

            else: # If no event is scheduled
                consecutive_active_slots = 0 # Reset consecutive work hours
                slot_recovery = RECOVERY_RATE ** SLOT_HOURS
                residual_fatigue *= slot_recovery # Reduce resididual fatigue by % value 
            
            if False: # Set to True to enable detailed logging of the simulation process
                if event is not None:
                    print(f"Hour {clock_hour}: Event: {event.name if event else 'Free'}, Predicted Energy: {predicted_energy}, Effective Energy: {effective_energy}, Task Yield: {task_yield if event else 'N/A'}, Residual Fatigue: {residual_fatigue}, S value: {s}")
                else:
                    print(f"Hour {clock_hour}: Event: Free, Predicted Energy: {predicted_energy}, Effective Energy: {effective_energy}, Residual Fatigue: {residual_fatigue}, S value: {s}")
            
            s = calculate_s(s) # Update S value 
        
        candidate.simulation_score = total_fitness # Store overall simulation score

        candidate.positive_yield_total = positive_yield_total
        candidate.negative_energy_penalty_total = negative_energy_penalty_total
        candidate.sleep_penalty_total = sleep_penalty_total
        candidate.fatigue_drain_total = fatigue_drain_total

    # Given a candidate Schedule object, fetch the individual and calculate an energy match & simulation fitness
    def evaluate_individual(self, candidate):

        candidate.reset_scores() # Reset scores to avoid adding to existing score
        SLOT_HOURS = SLOT_SIZE / 60

        for timeslot in candidate.timeslots: # Calculate energy match score for each timeslot
            if timeslot is not None:
                candidate.match_fitness += self.calculate_energy_match(timeslot.event, timeslot) * SLOT_HOURS

        self.simulate_schedule(candidate) # Simulate the candidate schedule

        candidate.total_fitness = candidate.simulation_score + candidate.match_fitness
        candidate.total_fitness -= candidate.unscheduled_events * UNSCHEDULED_EVENTS_PENALTY

    # Evaluate every individual in the population and record the top performers
    def evaluate_population(self, population):
  
        # TODO : Calculate best overall individual? Depends on discussion
        best_energy_match_score = -float('inf')
        best_simulation_score = -float('inf')

        best_match_individual = None
        best_simulation_individual = None

        for individual in population:
            self.evaluate_individual(individual)
            if individual.match_fitness > best_energy_match_score:
                best_energy_match_score = individual.match_fitness
                best_match_individual = individual
            if individual.simulation_score > best_simulation_score:
                best_simulation_score = individual.simulation_score
                best_simulation_individual = individual

        if False:
            print(f"Best energy match individual : ")
            best_match_individual.visualise()
            print(f"Best simulation individual : ")
            best_simulation_individual.visualise()

        return population

